### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#644]
Hi,
I got the following compilation error, any idea?

               from /home/reza/plato/PlatoSim3/dependencies/Downloads/googletest/googletest/src/gtest-all.cc:39:
/home/reza/anaconda2/envs/py3.7/x86_64-conda-linux-gnu/include/c++/9.3.0/ctime:80:11: error: '::timespec_get' has not been declared
   80 |   using ::timespec_get;
      |           ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/gtest.dir/build.make:63: CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/gtest.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "./dependencies/installscripts/install_googletest.py", line 59, in <module>
    shutil.copy(buildDir+packageName+"/googletest/build/libgtest.a",      installDir+"/lib/")
  File "/home/reza/anaconda2/envs/py3.7/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/reza/anaconda2/envs/py3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/reza/plato/PlatoSim3/dependencies/Downloads/googletest/googletest/build/libgtest.a'

**Comment by drsamadi** [comment]
this post
https://root-forum.cern.ch/t/error-timespec-get-has-not-been-declared-with-conda-root-package/45712/9
has solved my problem:

conda upgrade -c conda-forge --all
