### ISSUE TITLE
platonium crashes with wrong data type in numpy

### ISSUE THREAD

**Issue by guyrixon** [IvS-KULeuven/PlatoSim3#888]
(platosim) gtr@spartan05:~/platonium$ platonium --project smoke 1 1 1 1

PLATOnium

Initialize and configure PlatoSim

Applying platform jitter     (ACS RedNoise)
Traceback (most recent call last):
  File "/home/gtr/anaconda3/envs/platosim/bin/platonium", line 1626, in <module>
    sim = p.init_sim()
  File "/home/gtr/anaconda3/envs/platosim/bin/platonium", line 685, in init_sim
    self.rOA = np.rad2deg(rf.gnomonicRadialDistanceFromOpticalAxis(self.xFP, self.yFP,
  File "/home/gtr/platosim3/python/platosim/referenceFrames.py", line 1431, in gnomonicRadialDistanceFromOpticalAxis
    if isinstance(xFP, np.float):
  File "/home/gtr/anaconda3/envs/platosim/lib/python3.9/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

This happened with numpy==1.25. Conda can't find any previous versions to try instead.

**Comment by nicholasjannsen** [comment]
Hi Guy, 

thanks reporting this issue. I have just corrected this bug and pushed an update. 
Sorry for the inconvenience.
